name: myfirst work floww
on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps: 

            - name: git checkout 
              uses: actions/checkout@v4

            - name: Install cowsay program 
              run: sudo apt-get install cowsay -y

            - name: Excute cowsay program 
              run: cowsay -f dragon "Run for dog i am dog ..." >> dragon.txt

            - name: file exists
              run: grep -i "dragon"  dragon.txt

            - name: read files 
              run: cat dog.txt

            - name: welcome message
              run: echo "My first checking"
            
            - name: list files
              run: ls

            - name: Read files
              run: cat README.md
              

