name: Multilple Job demo

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout 
              uses: actions/checkout@v4

            - name: Installing cowsay command
              run: sudo apt-get install cowsay -y

            - name: Executing the cowsay 
              run: cowsay -f dragon "I am dragin, Run the code for dragon" >> dragon.txt

            - name: upload artifect
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt

    job2:
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: download artifect 
          uses: actions/download-artifact@v4
          with:
            name: dragon-file

        - name: read downloaded file
          run: cat dragon.txt